#cloud-config
version: v1
users:
  - name: local
  - name: ${vm_user_name}
    gecos: ${vm_user_displayname}
    passwd: ${vm_user_password}
    groups: sudo 
    lock_passwd: false
    shell: /bin/bash
    ssh_authorized_keys: ${vm_user_ssh_key}

apt:
  conf: |
    Acquire {
      Retries "60"
    }
    DPkg {
      Lock {
        Timeout "60"
      }
    }

package_update: true
packages_upgrade: true
packages:
  - ansible
  - ansible-core
  - net-tools
  - nmap
  - git
  - tree
  - openssh-server


#runcmd:
# -ansible-galaxy collection install kubernetes.coree
#  - git clone ${ansible_repo_url}
#  - cd ${ansible_repo_name}
#  - ansible-playbook ${ansible_playbook} -e "vm_ssh_port=${vm_ssh_port} esxi_host_name=${esxi_host_name} vsphere_host_ip=${vsphere_host_ip} vm_user_name=${vm_user_name} vnc_password=${vnc_password}"

# NEED TO ADD
# 1) nodes names to /etc/hosts
# 2) swapoff for kubelet
#
