#cloud-config
version: v1
users:
  - name: local
  - name: ${vm_user_name}
    gecos: ${vm_user_displayname}
    passwd: ${vm_user_password}
    groups: sudo 
    lock_passwd: false
    shell: /bin/bash
    ssh_authorized_keys: ${vm_user_ssh_key}

apt:
  conf: |
    Acquire {
      Retries "60"
    }
    DPkg {
      Lock {
        Timeout "60"
      }
    }

package_update: true
packages_upgrade: true
packages:
  - ansible
  - ansible-core
  - net-tools
  - nmap
  - git
  - tree
  - openssh-server

write_files:
## Add sysctl settings to support RKE's kernel-protect-defaults flag
  - content: |
      ${hosts_entry1}
      ${hosts_entry2}
      ${hosts_entry3}
      ${hosts_entry4}
      ${hosts_entry5}
    path: /home/${os_admin_username}/hosts_to_copy
    append: true
  - content: |
      ${vm_user_ssh_pk}
    path: /home/${os_admin_username}/.ssh/ansible_ed25519
  - content: | #how to write inventory before run Ansible???

      [masters]
      ${master0_ip}
      ${master1_ip}

      [workers]
      ${worker0_ip}
      ${worker1_ip}
      ${worker2_ip}

      [all:vars]
      ansible_connection=ssh
      ansible_user=${os_admin_username}
      ansible_ssh_pass=${vm_user_password}
      ansible_sudo_pass=${vm_user_password}
      ansible_ssh_private_key_file= /home/${os_admin_username}/.ssh/ansible_ed25519
    path: /home/${os_admin_username}/K8s-Lab  


runcmd:
 -ansible-galaxy collection install kubernetes.core
  - git clone ${ansible_repo_url}
  - cp /home/${os_admin_username}/K8s-Lab  /root/${ansible_repo_name}/Envinronments/K8s-Lab
  - cd ${ansible_repo_name}
  - ansible-playbook ${ansible_playbook} \
    -e "vsphere_host_ip=${vsphere_host_ip} \
        vsphere_server=${vsphere_server} \
        vsphere_user=${vsphere_user} \
        vsphere_password=${vsphere_password} \
        dcname=${dcname} \
        os_admin_username=${os_admin_username} \
        os_nic1_name=${os_nic1_name} \ 
        k8s_ver=${k8s_ver} \
        k8s_version_short=${k8s_version_short} \ 
        calico_version=${calico_version} \
        vsphere_csi_driver_version=${vsphere_csi_driver_version} \
        k8s_controlPlane_Endpoint=${k8s_controlPlane_Endpoint} \
        k8s_service_subnet=${k8s_service_subnet} \
        k8s_pod_subnet=${k8s_pod_subnet} \
        calico_network_cidr_blocksize=${calico_network_cidr_blocksize} \    
        k8s_cluster_id=${k8s_cluster_id} \
        sc_storage_policy_name=${sc_storage_policy_name} \
        sc_name=${sc_name}
        "


