#cloud-config
version: v1
users:
  - name: local
  - name: ${vm_user_name}
    gecos: ${vm_user_displayname}
    passwd: ${vm_user_password}
    groups: sudo
    lock_passwd: false
    shell: /bin/bash
    ssh_authorized_keys: ${vm_user_ssh_key}
apt:
  sources:
    ansible:
      source: deb https://ppa.launchpadcontent.net/ansible/ansible/ubuntu/ jammy main
      key: |
         -----BEGIN PGP PUBLIC KEY BLOCK-----
         Comment: Hostname: 
         Version: Hockeypuck 2.1.0-189-g15ebf24
         
         xsFNBFOXbTABEADKLcY3MYZyHIiCEu8cQ+0UzxZolTYZf8xZ06/d8xzUW/UBPTLV
         x/40IzWJEZU87GCYVXUhdYXECrFQKQOOEWQswBxOt26/g0nIrU0edZ9cCZ9o9+ZO
         sKDcScWNxWeclLr2+YHdmX9eph+2p+zIPmhNJaaWV6/bSo1fBi7ganZFRAc13zO8
         jtQsYyIeoAFwjt1vbk9CifdFhEchRVbwvZYhZDWfBZjhZ15UOunjo47gEkpK0PsW
         HY5N3/c75pGMwMTCjHMKno6KFzhdKLaz/QgbNnpy1aMkA/LITeU6Pgg6iqofrSY3
         Fx73MCAb8EEytvSV/65wztKzexHjGYxhm5ygoET5tPyXciX0+XzojkZAHzUEeT5z
         4kgL6OLyn+JQAyRDNnOJEkYmvwQveZuUjsYUkgc5DJdg6w7lTgQHWObOENpXls3B
         DnphA4DJyc0PQODCxdSZo4ZXMLn5lE/0qvAJ6g/wntY/ee/vRKwy9iDMOWQvihTI
         Y/L70/TnE4qZdaNbOJEvW59LT6GBTrcU1MX2fS5hU/mQa2CNixSVZG98rba3tfNa
         LDDNqivkcxtWryEWd0giBzzUS+MhtxhHm77YgxNVyyFn8bXb25/W+Jq+VvWWx2KD
         3ZwVD37X8wIBRLVozoH0jHVW7jKTnf2z+D6FCM+pVlm8zV1upXbHbdaRqwARAQAB
         zR9MYXVuY2hwYWQgUFBBIGZvciBBbnNpYmxlLCBJbmMuwsF4BBMBAgAiBQJTl20w
         AhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCTxKP9e7nDZwzdD/9yFq+3
         ptLyWP1JN3RXsvTIJLhhjOqMMJCOocV0G3slHeUtdIDmvd2RaS8PeFNSd9QFbUzk
         a7pBXec3a7kgEVorty2/+cZSpEVHT26oAbJnoH7E1YGii8bbnk9LqOCF/nLpasEq
         PKqtVzXz+vGB7G0ox8qmRm6JynrMeLBftYemxJ8e4fii6APJxE6FPz/AvgcN3BtB
         guseFwcga6lGcmp0JLofGhTbejfS9dW9bnCFJBtRfzUVd+Cb8aYuzV5zgCJgqOBJ
         Hf0L6xDwn8UuzRfi0MWzEskuC/KxUJqVHMuTaLdrSeP1/czompetbsSHTfDklf/p
         4EbSM9VqZFiKr17we0LdigAEv2JnL2Qj0oN3eRNU0sDJ3kZvh5qhnteNgSRM/el0
         Sly+34CRZzX25vd+pOTgwK6VFx3wvWfqn3pVNT9ASNalhogFXuBY2ukYJaiUTPsS
         R4+KHiD3eIhWyayBGP+GRvGb5dVC29k4CjLvQM9lISmZrrxGmMGoV9S1dh7siZYE
         CaVW0nKI95d6bBHaKH1g5HJ7NEsVTwf8LRY/FFpLsEPVw4HNVqqqwhuJnSW70WQ3
         blh0RIX/+z9hAla+M0kix7r0lS89ZBdTgwPuiCrkPRpoxi06ah/Q62uP3ZN4+dew
         1sBZdaC9kaKdOOWTqArVnaPObQgUUJFhY9wUsA==
         =uKv4
         -----END PGP PUBLIC KEY BLOCK-----
        
  conf: |
    Acquire {
      Retries "60"
    }
    DPkg {
      Lock {
        Timeout "60"
      }
    }

package_update: true
packages_upgrade: true
packages:
  - net-tools
  - nmap
  - git
  - tree
  - openssh-server
  - sshpass
  - software-properties-common
  - ansible
#  - ansible-core

write_files:
  - content: |
      # first hosts_entry - always vcloud hostname/ip
      ${hosts_entry0}
      ${hosts_entry1}

    path: /etc/hosts
    append: true

  - content: |
      #!/bin/bash
      export ip_net=$(echo ${master0_ip} | cut -d '.' -f1-3)
      export master0_ip_4=$(echo ${master0_ip} | cut -d '.' -f4)
      export worker0_ip_4=$(($(echo ${master0_ip} | cut -d '.' -f4)+${masters_count}))
      
      for (( m=0;m<=$((${masters_count}-1));m++ ));do ip=$((master0_ip_4 + m)); echo "$ip_net.$ip  ${master_pref}-$m" >> /etc/hosts; done
      for (( w=0;w<=$((${workers_count}-1));w++ ));do ip=$((worker0_ip_4 + w)); echo "$ip_net.$ip  ${worker_pref}-$w" >> /etc/hosts; done     
    path:  /add_hosts_records.sh
    permissions: "0744"

runcmd:
#  - add-apt-repository --yes --update ppa:ansible/ansible
  - /add_hosts_records.sh
  - sed -i 's/PasswordAuthentication no/#PasswordAuthentication no/' /etc/ssh/sshd_config
  - [ systemctl, daemon-reload ]
  - [ systemctl, restart, --no-block, ssh.service ]
  - [ ansible-galaxy, collection, install, kubernetes.core ]
